services:
  - type: web
    name: orkester-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false

  - type: web
    name: orkester-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: orkester-api
          property: host
